version: "3.8"

services:
  keycloak:
    build:
      context: .
      dockerfile: Dockerfile.keycloak-java25
      args:
        KEYCLOAK_VERSION: ${KEYCLOAK_VERSION:-26.6.1}
    command:
      - start-dev
      - --debug
      - --verbose
      - --features=dpop
      - --import-realm
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_LOG_LEVEL: info,de.arbeitsagentur.keycloak.push:debug
      GOOGLE_APPLICATION_CREDENTIALS: /var/secrets/google-service-account.json
      KC_SPI_PUSH_NOTIFICATION_SENDER__FCM_PROVIDER__GOOGLE_FCM_URL: http://pushmfa-simulator:5000/fcm/messages:send
    ports:
      - "8080:8080"
      - "8787:8787"
    volumes:
      - ./target/keycloak-push-mfa-extension.jar:/opt/keycloak/providers/keycloak-push-mfa.jar:ro
      - ./config:/opt/keycloak/data/import:ro
      - ./mock/mock-google-credentials.json:/var/secrets/google-service-account.json:ro
  pushmfa-simulator:
    image: ghcr.io/ba-itsys/keycloak-push-mfa-extension-simulator:v1.12.2
    ports:
      - "5000:5000"
    environment:
      SERVER_SERVLET_CONTEXT_PATH: "/"
      APP_CLIENTID: push-device-client
      APP_CLIENTSECRET: device-client-secret
      APP_PROVIDERIDS: log,fcm-provider,none
      APP_LOCALHOSTREPLACEMENT: keycloak
    volumes:
      - ./mock/mock-rsa-jwk.json:/app/static/keys/rsa-jwk.json
